# 公共配置文件
spring:
  application:
    name: nimble-api-backend
#在application.properties/或者application.yml文件中没有添加数据库配置信息.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: hsp
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8101
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    urlPrefix: http://nimble-api-project.oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${accessKeyId}
    accessKeySecret: ${accessKeySecret}
    bucketName: alylmengbucket
    fileHost: cache

# 这段配置仅供测试，实际应该根据登录用户获取对应的 ak、sk，仅供测试用
yuapi:
  client:
    access-key: yupiapi
    secret-key: 12345678

# Dubbo配置和Nacos
dubbo:
  application:
    name: nimble-api-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

# 网关接口配置
nimble:
  gateway:
    host: http://localhost:8103